### ISSUE TITLE
Create a flexible HTCondor job/DAG workflow templating system

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/htcondor-tools#1]
Here's my current thinking on how to do this (feel free to suggest alternative solutions):

Instead of editing job files, users would put all their job/DAG workflow settings into a single JSON file, something like this for a single job:

``` json
{
    "jobs" : [
        {
            "name" : "job0",
            "universe" : "vanilla",
            "getenv" : "true",
            "accounting_group" : "$ENV(CONDOR_GROUP)",
            "notification" : "complete",
            "request_cpus" : "8",
            "request_memory" : "2G",
            "executable" : "bowtie2",
            "arguments" : "-foo -bar",
            "log" : "$(Cluster).$(Process).bowtie2.log",
            "output" : "$(Cluster).$(Process).bowtie2.out",
            "error" : "$(Cluster).$(Process).bowtie2.error"
        }
    ]
}
```

and maybe like this for a DAG workflow

``` json
{
    "dag" : [
        {
            "name" : "job0",
            "universe" : "vanilla",
            "getenv" : "true",
            "accounting_group" : "$ENV(CONDOR_GROUP)",
            "notification" : "complete",
            "request_cpus" : "8",
            "request_memory" : "2G",
            "executable" : "bowtie2",
            "arguments" : "-foo -bar",
            "log" : "$(Cluster).$(Process).bowtie2.log",
            "output" : "$(Cluster).$(Process).bowtie2.out",
            "error" : "$(Cluster).$(Process).bowtie2.error",
            "child" : "job1"
        },
        {
             "name" : "job1",
             "..." : "..."
        }
    ]
}
```

Then have a Python script read the JSON and create the necessary job and DAG files. @calizarr also added the idea of using jinja as a templating tool to insert the values from the JSON into job/DAG template files.

**Comment by afinit** [comment]
So it's possible to just submit jobs from the command line. I've been designing my workflow scripts to write jobfiles and run them for the purpose of documenting. However if this works well, I don't see why these files couldn't serve that purpose.

We could just provide a "debug" option or something that would output the jobfiles.

In a JSON file or other format, we will be able to include variables for multiple submits. So instead of providing 25 lines in a condor_input file to run 25 HISAT jobs, we could just add 25 entries to a section in the JSON:

```
{
    "input": {
        "job0": [20, "/path/to/reads", "other input"],
        "...":[..., ..., ...]
    }
}
```

or something like this

**Comment by nfahlgren** [comment]
@afinit agreed, having a way to input this same thing on these n inputs would be great.

For DAG workflows I think we will need the condor job files, since you have to specify them in the workflow file. There is also an htcondor Python module where you can create job classads directly, but I think it's the same problem where it would not work for DAG (although not sure).

**Comment by nfahlgren** [comment]
@kbgilbert just mentioned that she figured out you can insert variables into the DAG file that get used by the jobs, so that could be an alternative to jinja as a way to insert variables into jobfile templates.

**Comment by kbgilbert** [comment]
Like Noah mentioned, I think I've worked out how to have a 'Master DAGman' file that has all the jobfile-specific info that then gets fed into individual jobfiles... still working out the kinks though.

In the mean time, came across this in the DAGman manual about when you have 'Large Numbers of Jobs' to submit...
http://research.cs.wisc.edu/htcondor/manual/v8.2/2_10DAGMan_Applications.html#SECTION0031015000000000000000
